# Loan Approval Prediction System

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("loan_data.csv")

In [6]:
df.shape

(45000, 14)

In [7]:
df.sample(5)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
40178,36.0,male,Bachelor,57773.0,11,RENT,4892.0,DEBTCONSOLIDATION,11.90,0.08,10.0,624,Yes,0
2280,24.0,male,Master,47858.0,1,RENT,13000.0,EDUCATION,10.75,0.27,4.0,670,No,1
18173,30.0,female,Bachelor,199083.0,6,MORTGAGE,5000.0,EDUCATION,15.62,0.03,10.0,560,Yes,0
25285,31.0,female,Master,72959.0,10,RENT,12000.0,HOMEIMPROVEMENT,7.49,0.16,10.0,687,No,0
31927,46.0,female,High School,10510.0,24,RENT,1600.0,MEDICAL,14.42,0.15,11.0,677,No,1

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  str
 2   person_education                45000 non-null  str
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  str
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  str
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  str
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), str(5)
memory usage: 4.8 MB

In [9]:
df.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,loan_status
count,45000.000000,4.500000e+04,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,27.764178,8.031905e+04,5.410333,9583.157556,11.006606,0.139725,5.867489,632.608756,0.222222
std,6.045108,8.042250e+04,6.063532,6314.886691,2.978808,0.087212,3.879702,50.435865,0.415744
min,20.000000,8.000000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,390.000000,0.000000
25%,24.000000,4.720400e+04,1.000000,5000.000000,8.590000,0.070000,3.000000,601.000000,0.000000
50%,26.000000,6.704800e+04,4.000000,8000.000000,11.010000,0.120000,4.000000,640.000000,0.000000
75%,30.000000,9.578925e+04,8.000000,12237.250000,12.990000,0.190000,8.000000,670.000000,0.000000
max,144.000000,7.200766e+06,125.000000,35000.000000,20.000000,0.660000,30.000000,850.000000,1.000000

In [12]:
# OneHotEncoding
df["person_gender"].value_counts()

person_gender
male      24841
female    20159
Name: count, dtype: int64

In [13]:
# OrdinalEncoding
df["person_education"].value_counts()

person_education
Bachelor       13399
Associate      12028
High School    11972
Master          6980
Doctorate        621
Name: count, dtype: int64

In [14]:
# OneHotEncoding
df["person_home_ownership"].value_counts()

person_home_ownership
RENT        23443
MORTGAGE    18489
OWN          2951
OTHER         117
Name: count, dtype: int64

In [15]:
# OneHotEncoding
df["loan_intent"].value_counts()

loan_intent
EDUCATION            9153
MEDICAL              8548
VENTURE              7819
PERSONAL             7552
DEBTCONSOLIDATION    7145
HOMEIMPROVEMENT      4783
Name: count, dtype: int64

In [16]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [17]:
df["previous_loan_defaults_on_file"]=df["previous_loan_defaults_on_file"].replace({
    "Yes": 1,
    "No":0
})

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:13],df.iloc[:,-1],test_size=0.2)

In [19]:
print(f"Train size: {x_train.shape}, Test size: {x_test.shape}")

Train size: (36000, 13), Test size: (9000, 13)

In [20]:
x_train

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
14977,25.0,female,Associate,61378.0,5,RENT,15000.0,VENTURE,11.14,0.24,4.0,559,0
11556,23.0,male,Associate,79791.0,0,RENT,10000.0,MEDICAL,9.32,0.13,4.0,668,1
771,22.0,male,Master,93070.0,0,RENT,20000.0,EDUCATION,13.79,0.21,4.0,662,0
7453,23.0,male,Bachelor,57255.0,0,MORTGAGE,16000.0,MEDICAL,14.35,0.28,3.0,687,0
21539,27.0,male,Associate,58341.0,2,MORTGAGE,20000.0,VENTURE,11.89,0.34,10.0,565,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8203,23.0,female,High School,68131.0,0,MORTGAGE,10000.0,MEDICAL,8.59,0.15,3.0,580,1
2946,26.0,female,Associate,43029.0,4,OWN,7200.0,PERSONAL,11.11,0.17,4.0,672,0
24171,29.0,female,Bachelor,84781.0,6,OWN,13000.0,VENTURE,6.91,0.15,8.0,675,1
16334,22.0,female,Bachelor,58246.0,1,RENT,4000.0,VENTURE,11.01,0.07,3.0,541,0
15155,23.0,male,Bachelor,151219.0,2,MORTGAGE,35000.0,EDUCATION,8.90,0.23,4.0,561,1

In [21]:
duplicates = pd.merge(x_train, x_test, how='inner')
print(f"Duplicate rows between train/test: {len(duplicates)}")

Duplicate rows between train/test: 0

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [23]:
transformer=ColumnTransformer(transformers=[
    ("tnf1",OneHotEncoder(drop="first",sparse_output=False,handle_unknown="ignore"),["person_gender","person_home_ownership","loan_intent"]),
    ("tnf2",OrdinalEncoder(categories=[["High School","Associate","Bachelor","Master","Doctorate"]]),["person_education"]),
    ("tnf3",StandardScaler(),["person_income","loan_amnt","credit_score"])
],remainder="passthrough")

In [24]:
x_train=transformer.fit_transform(x_train)
x_test=transformer.transform(x_test)

In [25]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1000)

In [26]:
lr.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [27]:
prediction=lr.predict(x_test)
prediction

array([1, 0, 0, ..., 0, 0, 0], shape=(9000,))

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy=accuracy_score(y_test,prediction)*100

In [30]:
print(f"Accuracy : {accuracy} %")

Accuracy : 89.72222222222223 %

In [31]:
train_acc = lr.score(x_train, y_train)  # This will be high — don't use this
test_acc  = lr.score(x_test, y_test)    # This is the real accuracy

print(f"Train Accuracy: {train_acc:.4f}")
print(f"Test Accuracy:  {test_acc:.4f}")

Train Accuracy: 0.8968
Test Accuracy:  0.8972

In [32]:
# Check how many features the model actually has
print(f"Model features: {lr.coef_[0].shape[0]}")

# If you used OneHotEncoder or get_dummies, get names like this
print(f"X_train columns: {x_train.shape[1]}")

Model features: 19
X_train columns: 19

In [33]:
feature_names = [
    'person_age',
    'person_gender_male',
    'person_education',
    'person_income',
    'person_emp_exp',
    'person_home_ownership_MORTGAGE',
    'person_home_ownership_OTHER',
    'person_home_ownership_OWN',
    'loan_amnt',
    'loan_intent_DEBTCONSOLIDATION',
    'loan_intent_EDUCATION',
    'loan_intent_HOMEIMPROVEMENT',
    'loan_intent_MEDICAL',
    'loan_intent_VENTURE',
    'loan_int_rate',
    'loan_percent_income',
    'cb_person_cred_hist_length',
    'credit_score',
    "previous_loan_defaults_on_file"
]

importances = pd.Series(
    np.abs(lr.coef_[0]),
    index=feature_names
).sort_values(ascending=False)

print(importances)

cb_person_cred_hist_length        13.971421
previous_loan_defaults_on_file     7.800598
person_education                   1.287592
loan_amnt                          1.159238
person_emp_exp                     0.918035
person_income                      0.736283
person_home_ownership_OWN          0.711778
loan_intent_HOMEIMPROVEMENT        0.517087
loan_intent_MEDICAL                0.441575
loan_percent_income                0.315595
person_home_ownership_OTHER        0.296968
person_gender_male                 0.105904
person_home_ownership_MORTGAGE     0.058095
person_age                         0.025227
loan_intent_VENTURE                0.021406
loan_int_rate                      0.016340
credit_score                       0.011281
loan_intent_EDUCATION              0.004479
loan_intent_DEBTCONSOLIDATION      0.001883
dtype: float64

In [35]:
import pickle

# Save
with open("transformer.pkl", "wb") as f:
    pickle.dump(transformer, f)

with open("loan_prediction_model.pkl", "wb") as f:
    pickle.dump(lr, f)

print("Saved.")

# Immediately verify they load correctly, right here, before moving them anywhere
with open("transformer.pkl", "rb") as f:
    test_transformer = pickle.load(f)

with open("loan_prediction_model.pkl", "rb") as f:
    test_model = pickle.load(f)

print("Both files loaded successfully:", type(test_transformer), type(test_model))

Saved.
Both files loaded successfully: <class 'sklearn.compose._column_transformer.ColumnTransformer'> <class 'sklearn.linear_model._logistic.LogisticRegression'>